### PR TITLE
Added npm install instructions to readme

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amilajack** [comment]
@adamdbradley The npm package [ionicons](https://www.npmjs.com/package/ionicons) has you as it's author so installing from npm should be save. This is a PR adding the npm installation method to the readme.

**Comment by ramonsan** [comment]
`+Or npm [bower](http://bower.io/)?` it should not be like `+Or npm [npm](https://www.npmjs.com/)?` at line 30?

**Comment by speyburn** [comment]
@amilajack would you like to make the changes so this could be merged in? :) 

I can make a PR for this one also (since its the second time in a short while i stumble upon the fact that npm is not mentioned in the readme) but since there is already an open one for the same subject it should maybe be closed / resolved first.

**Comment by amilajack** [comment]
So I should close this. Correct?

**Pull request closed without merging**
